### ISSUE TITLE
[DOUBT] Buttons are not visible in light mode

### ISSUE THREAD

**Issue by dhruv-ahuja** [not-matthias/apollo#19]
Hey I was trying out the theme today (looks really clean by the way :D) and saw that the light mode hides the buttons. I wanted to know whether this is intentional or not as they are visible with the dark theme. 

I switched between the themes by manually setting the default value in the partials/header.html file.

Light Mode:
![image](https://github.com/not-matthias/apollo/assets/83733638/da21d259-e24c-419a-b6b0-1dff4e9bfc28)

Dark Mode:
![image](https://github.com/not-matthias/apollo/assets/83733638/24aa543f-c415-4092-9e24-0927b33c5059)

**Comment by dhruv-ahuja** [comment]
Okay so I've figured out what the issue was. 
Disabling or moving this piece of code to dark.scss file fixes the issue: 
```scss
@media (prefers-color-scheme: dark) {
  .social > img {
    filter: invert(1);
  }
}
```
Not sure why but this property is being applied even when we set "light" as the theme value. 

I removed the `@media` call and just added the rest of the code as it is into the root element and that worked.

**Comment by not-matthias** [comment]
Thanks for investigating this! Feel free to create a pull request with the changes.

**Comment by dhruv-ahuja** [comment]
Cool, will do that! Also, I had forked the repo to make some other modifications to theme as per my liking, one of which is adding a toggle button, similar to the one in Archie-zola. I have used the icon logic from there but the underlying logic is a bit different. 
Would you be interested in having this functionality in the Apollo theme? If so, I can create a PR with this logic in place, else I can make the PR with just the changes for the icon visibility.

[Here's](https://github.com/dhruv-ahuja/apollo/tree/custom) the link to my fork's branch with the code. 

Here's screenshots of the toggle button:
light theme:
![image](https://github.com/not-matthias/apollo/assets/83733638/9bd9a63b-ced2-4bee-8ba1-48c76c433426)
 
dark theme:
![image](https://github.com/not-matthias/apollo/assets/83733638/c0b45e80-55f7-44a0-b250-39900d5f468b) 

Thanks!

**Comment by dhruv-ahuja** [comment]
hey, any update regarding this?

**Comment by not-matthias** [comment]
Sorry, didn't see the message and was busy with university. I'd love to have a theme toggle button! :D

**Comment by dhruv-ahuja** [comment]
created the PR 👍
