### ISSUE TITLE
Build and Deploy GH pages failed

### ISSUE THREAD

**Issue by sidchintamaneni** [not-matthias/apollo#21]
I have included the apollo theme as a submodule to my blog but there is an issue at build_and_deploy step. I will put down the errors below.

Error: Failed to build the site
Error: Error parsing templates from the /templates directory
Error: Reason: Io error while writing rendered value to output: NotFound
Error: Reason: Io error while writing rendered value to output: NotFound

I have tested in my local and it is working fine

**Comment by not-matthias** [comment]
If you still have this issue, feel free to reopen the issue. If you figured it out, you can mention how you solved it if others have the same issue.
