### ISSUE TITLE
MathJax not rendering

### ISSUE THREAD

**Issue by rtedwards** [not-matthias/apollo#23]
MathJax is not rendering

<img width="1161" alt="Screenshot 2023-07-24 at 09 56 31" src="https://github.com/not-matthias/apollo/assets/46866563/511bfbba-b024-4762-84e0-a0e0d3270483">

**Comment by not-matthias** [comment]
You need to enable it in the config: 
```
mathjax = true
mathjax_dollar_inline_enable = true
```

After doing that, it works as expected:
![image](https://github.com/not-matthias/apollo/assets/26800596/ae382012-b958-4e79-890e-12c2e87ac47d)
