### ISSUE TITLE
Improvement suggestion to `themetoggle.js` - don't default to light 

### ISSUE THREAD

**Issue by jmetz** [not-matthias/apollo#26]
For my purposes I created a new version of the `themetoggle.js` which defaults to the auto value.

Basically the same as before except: 

```js 
var currentTheme = localStorage.getItem("theme-storage");
if(!currentTheme){
    if (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) {
        currentTheme = "dark";
    } else {
        currentTheme = "light";
    }
}
setTheme(currentTheme);
```

ie. don't default to `light`.

I'm sure the above is a bit clunky and can be refined, but it gets the job done!

**Comment by not-matthias** [comment]
Thanks for reporting!
