### ISSUE TITLE
Add social icon of x-twitter

### ISSUE THREAD

**Issue by boykush** [not-matthias/apollo#39]
Hello.

This is a minor suggestion, I would like to add an X (twitter) icon to social icons.

If you don't mind, I'll submit a pull request for the same commit as [this](https://github.com/boykush/apollo/pull/3) pull request.

**Comment by boykush** [comment]
As a side note, the svg file in the pull request is a file downloaded from font awesome in accordance with LICENSE.

Link: https://fontawesome.com/icons/x-twitter?f=brands&s=solid

**Comment by not-matthias** [comment]
Hey, feel free to create a pull request :)
