### ISSUE TITLE
Taxonomy not working as expected

### ISSUE THREAD

**Issue by harish-coeff** [not-matthias/apollo#45]
Tried to use taxonomy for tags, it was not working as expected? can you add instructions, I am not sure how the config, usage differs when compared to [archie-zola](https://github.com/XXXMrG/archie-zola/tree/cc39947e4c11ee074e045d97a4e8c7220e7fcfdf)

**Comment by harish-coeff** [comment]
The PR i raised worked for me, it's taken from archie-zola

**Comment by not-matthias** [comment]
Fixed by #46
