### ISSUE TITLE
Does apollo support comment system?

### ISSUE THREAD

**Issue by donghao1393** [not-matthias/apollo#49]
If I am going to support comment for visitors, what should we do?
Would it support [giscuss](https://giscus.app) just like other themes [serene](https://www.getzola.org/themes/serene/) and [minimal-dark](https://www.getzola.org/themes/minimal-dark/)?

**Comment by not-matthias** [comment]
Currently not implemented but you can easily extend the post template to include giscuss/utterances. Feel free to create a PR!
