### ISSUE TITLE
issues when setting theme(dark/light/toggle/auto) in config.toml

### ISSUE THREAD

**Issue by 0xAndyB** [not-matthias/apollo#54]
When setting the color theme from toggle to dark in the config.toml, the site goes to black and white. Can't find where this is coming from in the files.
![Screenshot from 2024-04-19 19-20-32](https://github.com/not-matthias/apollo/assets/66244170/3326f9b2-848c-48c2-ad3c-38bb6daf3dc6)

**Comment by not-matthias** [comment]
Thanks for reporting. I'll investigate
