### ISSUE TITLE
Add a home page

### ISSUE THREAD

**Issue by SeniorMars** [not-matthias/apollo#59]
I implemented this for my fork, and I thought perhaps some people might want this too.

Anyway, right now index.html just redirects to /posts. This is fine, but sometimes people want a landing page. Here is mine: https://seniormars.com/.

I already have the code needed for this, but I'm unsure if this is feature that should be pred.

**Comment by not-matthias** [comment]
Yeah, seems like a feature that can be useful for others :+1:

**Comment by SeniorMars** [comment]
The only problem is that I couldn't figure out a way to disable this by default in a clean fashion, as we would be modifying the index.html. We could create a hacky solution but it will be messy.

**Comment by not-matthias** [comment]
You should be able to set a custom template using the following config (like I did in the projects _index.md)
```
template = "homepage.html"
```

So default `index.html` is the normal page view. And you can opt in to use a different template as homepage.
