### ISSUE TITLE
Language name not visible

### ISSUE THREAD

**Issue by not-matthias** [not-matthias/apollo#60]
Name of some languages isn't visible:
![image](https://github.com/not-matthias/apollo/assets/26800596/e5b82398-da09-4992-878d-af407cea6254)

See: https://not-matthias.github.io/apollo/posts/shortcode/

---

@SeniorMars can you check this out?

**Comment by not-matthias** [comment]
Same issue for markdown: 
![image](https://github.com/not-matthias/apollo/assets/26800596/1ee61aa7-94ff-4ac7-a3de-1add53aa4dcf)

(happens only with the light theme)

**Comment by SeniorMars** [comment]
I was kinda aware of this issue...i just forgot. Yea I'll fix it, I just use dark mode always so I forgot.
