### ISSUE TITLE
Theme Install Issues

### ISSUE THREAD

**Issue by Zie0** [not-matthias/apollo#66]
Thanks for making this cool looking theme! I think this looks great, but I can't get it setup following the instructions in the README.md.

What is the most recent version of zola that this theme supports? I tried three major versions because I saw https://github.com/not-matthias/apollo/issues/65 

If I'm understanding correctly, [this says the min zola version is 0.14.0](https://github.com/Zie0/apollo/blob/main/theme.toml#L3). I'm getting a series of errors when I follow the three README.md steps when using zola `0.19.0`, `0.18.0` and `0.14.0`. Given that note about zola `0.14.0` I saw I thought I'd give that a try too. That gave me the same errors on setup, each time from a fresh zola filetree. I've documented them in hopes this helps find a resolution. Thanks

# Zola `0.18.0` and `0.19.0` Setup Errors

After completing [this step](https://github.com/Zie0/apollo/blob/main/README.md?plain=1#L43) I get the following errors with the above versions of zola.
```
% zola serve                                                                         24-06-29 - 22:29:07
Building site...
Error: Failed to serve the site
Error: Page `./content/posts/markdown.md` has taxonomy `tags` which is not defined in config.toml
```

When I remove [lines 6 and 7](https://github.com/Zie0/apollo/blob/main/content/posts/markdown.md?plain=1#L6) from `./content/posts/markdown.md` the next error I encounter is 

```
% zola serve                                                                    :( 1 24-06-29 - 22:37:52
Building site...
Checking all internal links with anchors.
> Successfully checked 0 internal link(s) with anchors.
-> Creating 10 pages (0 orphan) and 2 sections
Error: Failed to serve the site
Error: Failed to render page './content/about.md'
Error: Reason: Failed to render 'page.html' (error happened in 'base.html').
Error: Reason: Variable `config.extra.theme` not found in context while rendering 'partials/header.html'
```

To me this indicates that [theme = "apollo"](https://github.com/Zie0/apollo/blob/main/README.md?plain=1#L39) must be set under the `[extra]` header in the config.toml. I'm confused because this doesn't match [the zola documentation.](https://www.getzola.org/documentation/getting-started/configuration/)

> make sure to place the variable in the top level of the .toml hierarchy and not after a dict like [extra] or [markdown]
-- [using a theme](https://www.getzola.org/documentation/themes/installing-and-using-themes/#using-a-theme)

This was the last error I encountered after moving `theme = "apollo"` under the `[extra]` header in the onfig.toml before I gave up using this on zola  `0.19.0`, `0.18.0`, and  `0.14.0`
```
% zola serve                                                                    :( 1 24-06-29 - 22:42:41
Building site...
Error: Failed to serve the site
Error: Failed to render content of ./content/posts/shortcode.md
Error: Reason: Found usage of a shortcode named `note` but we do not know about. Make sure it's not a typo and that a field name `note.{html,md} exists in the `templates/shortcodes` directory.
```

**Comment by not-matthias** [comment]
I'll investigate. Thanks for reporting

**Comment by not-matthias** [comment]
@Zie0 I fixed the installation instructions. Please retry it: https://github.com/not-matthias/apollo?tab=readme-ov-file#installation

Things that changed: 
- `cp` command was wrong (accidentally copied the folder inside the folder leading to `content/content/*` instead of `content/*`)
- Add needed `[extra]` options and make it more clear
