### ISSUE TITLE
Enable comments only on post pages

### ISSUE THREAD

**Issue by rproskuryakov** [not-matthias/apollo#74]
Hi! I'd like to enable comments only for blog pages. It seems to me that the current way to configure (extra.comment = true) enables comments on all of the site pages. Can I do what I need with the current theme state?

**Comment by not-matthias** [comment]
I'll investigate, thanks for reporting!

**Comment by not-matthias** [comment]
Should be fixed now. Comments can now only be configured in the individual pages, see the documentation here: https://not-matthias.github.io/apollo/posts/configuration/#comments-comment

If you have any further issues or notice lacking things in the documentation, feel free to create a pull request or issue! :)

**Comment by rproskuryakov** [comment]
Thank you!
