### ISSUE TITLE
Site will not build

### ISSUE THREAD

**Issue by mroberts1** [not-matthias/apollo#9]
I keep getting this error and can't figure out what the problem is. I tried commenting out and deleting the socials section of nav.html but the result is always the same.

```
Error: Failed to serve the site
Error: Failed to render page '/Users/dokoissho/GitHub/zola/apollo/content/about.md'
Error: Reason: Failed to render 'page.html' (error happened in 'base.html').
Error: Reason: Variable `config.extra.socials` not found in context while rendering 'partials/nav.html'
```

**Comment by not-matthias** [comment]
Could you share your `config.toml`? Here's the `config.toml` of my blog which might be useful: https://github.com/not-matthias/not-matthias.github.io/blob/main/config.toml

**Comment by mroberts1** [comment]
Thanks for responding and sorry for the lagged follow-up - I copied in your own config.toml and got a couple of errors in line 24 - in the socials section - due to a syntax error, an unexpected line break that separated icon and =.  When I restored the line to icon= "twitter" and icon= "github", the site was served. So that seems to have fixed it - thanks again, it's a nice theme.

**Comment by not-matthias** [comment]
Glad to hear everything is working now. I'll close this, but feel free to reopen it if it fails again.
